# Generated by Django 4.2.1 on 2024-08-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('machine', models.CharField(max_length=100)),
                ('component', models.CharField(max_length=100)),
                ('parameter', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('failure', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='username',
            field=models.CharField(max_length=100, unique=True, verbose_name='User Name'),
        ),
    ]
