# Generated by Django 4.2.1 on 2024-08-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_history_alter_customusermodel_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=100)),
                ('Recommendations1', models.CharField(max_length=300, null=True)),
                ('Recommendations2', models.CharField(max_length=300, null=True)),
                ('Recommendations3', models.CharField(max_length=300, null=True)),
                ('Recommendations4', models.CharField(max_length=300, null=True)),
                ('Recommendations5', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
